
    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    

    '***************************************************
    'Function maps
    '***************************************************
    function RBSFM_getFunctionsForFile(filename)
  map = {
    "test_ParserModule":RBSFM_getFunctions_test_ParserModule 
  } 
  return map[filename]
end function

function RBSFM_getFunctions_test_ParserModule()
  return {
    "PM_setUp":PM_setUp 
    "PM_isDefined":PM_isDefined 
    "PM_interface":PM_interface 
    "PM_parseSetsValues":PM_parseSetsValues 
    "PM_parseEntriesSetsValues":PM_parseEntriesSetsValues 
    "PM_parseEntrySetsValues":PM_parseEntrySetsValues 
  } 

end function

function RBSFM_getFilenames()
  return [
    "test_ParserModule", 
  ] 
end function



    '***************************************************
    ' Unit test suites defitintions
    '***************************************************
    

    function RBSFM_getTestSuitesForProject()
        return [
        
{
      name: "[PM] Parser Module Tests"
      filePath: "pkg:/app/source/tests/specs/data/test_ParserModule.brs"
      valid: true
      hasFailures: false
      hasSoloTests: false
      hasIgnoredTests: false
      hasSoloGroups: false
      isSolo: false
      isIgnored: false
      itGroups: [
      {
        testCases: [
        {
          isSolo: false
          funcName: "PM_isDefined"
          isIgnored: false
          isParamTest: false
          name: "ParserModule is defined"
          lineNumber: 14
          paramLineNumber: 0
          assertIndex: 1
          assertLineNumberMap: {"0":15}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "PM_interface"
          isIgnored: false
          isParamTest: false
          name: "ParserModule interface is as expected"
          lineNumber: 19
          paramLineNumber: 0
          assertIndex: 4
          assertLineNumberMap: {"0":20,"1":21,"2":22,"3":23}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "test_ParserModule"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: "PM_setUp"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests ParserModule is defined"
      },
      {
        testCases: [
        {
          isSolo: false
          funcName: "PM_parseSetsValues"
          isIgnored: false
          isParamTest: false
          name: "Parse sets the correct values on the collection node model"
          lineNumber: 31
          paramLineNumber: 0
          assertIndex: 4
          assertLineNumberMap: {"0":41,"1":42,"2":43,"3":44}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "test_ParserModule"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: "PM_setUp"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests Parse method"
      },
      {
        testCases: [
        {
          isSolo: false
          funcName: "PM_parseEntriesSetsValues"
          isIgnored: false
          isParamTest: false
          name: "ParseEntries appends children to collectio node"
          lineNumber: 54
          paramLineNumber: 0
          assertIndex: 4
          assertLineNumberMap: {"0":66,"1":72,"2":73,"3":74}
          rawParams: []
          paramTestIndex: 0
          expectedNumberOfParams: 0
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "test_ParserModule"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: "PM_setUp"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests ParseEntries method"
      },
      {
        testCases: [
        {
          isSolo: false
          funcName: "PM_parseEntrySetsValues"
          isIgnored: false
          isParamTest: true
          name: "ParseEntry sets the correct values on the video node model0"
          lineNumber: 86
          paramLineNumber: 83
          assertIndex: 3
          assertLineNumberMap: {"0":96,"1":97,"2":98}
          rawParams: [{"type":"video","title":"Thisisvideo1","summary":"Thisisthesummaryforvideo1.","id":"video_001"}]
          paramTestIndex: 0
          expectedNumberOfParams: 1
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "PM_parseEntrySetsValues"
          isIgnored: false
          isParamTest: true
          name: "ParseEntry sets the correct values on the video node model1"
          lineNumber: 86
          paramLineNumber: 84
          assertIndex: 3
          assertLineNumberMap: {"0":96,"1":97,"2":98}
          rawParams: [{"type":"","title":"","summary":"","id":""}]
          paramTestIndex: 1
          expectedNumberOfParams: 1
          isParamsValid: true
        },
        {
          isSolo: false
          funcName: "PM_parseEntrySetsValues"
          isIgnored: false
          isParamTest: true
          name: "ParseEntry sets the correct values on the video node model2"
          lineNumber: 86
          paramLineNumber: 85
          assertIndex: 3
          assertLineNumberMap: {"0":96,"1":97,"2":98}
          rawParams: [{"type":123,"title":"Satan <3","summary":"The devil inside me!","id":"video_666"}]
          paramTestIndex: 2
          expectedNumberOfParams: 1
          isParamsValid: true
        }]
        ignoredTestCases: []
        soloTestCases: []
        filename: "test_ParserModule"
        setupFunctionName: ""
        tearDownFunctionName: ""
        beforeEachFunctionName: "PM_setUp"
        afterEachFunctionName: ""
        isSolo: false
        isIgnored: false
        hasSoloTests: false
        name: "tests ParseEntry method"
      }]
      setupFunctionName: ""
      tearDownFunctionName: ""
      isNodeTest: false
      nodeTestFileName: ""
      beforeEachFunctionName: "PM_setUp"
      afterEachFunctionName: ""
    },

      ]
    end function



    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    